apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graphql
  namespace: argocd
spec:
  project: ecommerce-platform
  source:
    repoURL: https://github.com/luisllm/demo-argocd-datree-config.git
    targetRevision: HEAD
    path: "application-charts/graphql"
    helm:
      valueFiles: ['values-dev.yaml'] # resolved against source.repoURL and source.path
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true