apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ecommerce-platform
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: ecommerce-platform
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Only permit applications to deploy to the ecommerce namespace in the same cluster
  destinations:
  - namespace: ecommerce
    server: https://kubernetes.default.svc