#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: podinfo
#  namespace: argocd
#spec:
#  project: podinfo-project
#  source:
#    repoURL: https://github.com/luisllm/demo-argocd-datree-config.git
#    targetRevision: HEAD
#    path: "application-charts/podinfo"
#    helm:
#      valueFiles: ['values-dev.yaml'] # resolved against source.repoURL and source.path
#  destination:
#    server: https://kubernetes.default.svc
#    namespace: demo
#  syncPolicy:
#    automated:
#      selfHeal: true


# https://codefresh.io/blog/how-to-model-your-gitops-environments-and-promote-releases-between-them/
# https://github.com/argoproj/argo-cd/issues/2789
# https://stackoverflow.com/questions/65897034/argocd-helm-chart-repository-not-accessible?rq=3
# https://betterprogramming.pub/how-to-promote-releases-between-gitops-environments-2b5304de5f28

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
spec:
  project: podinfo-project
  sources:
    - repoURL: https://github.com/luisllm/demo-helm-charts.git
      path: podinfo
      targetRevision: HEAD
      helm:
        valueFiles:
          - $repo-1/envs/develop/podinfo-values.yaml
          - $repo-1/envs/develop/podinfo-version.yaml
    - repoURL: https://github.com/luisllm/demo-argocd-datree-config.git
      targetRevision: HEAD
      ref: repo-1
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true